[project]
name = "bd2"
version = "0.1.0"
description = "Dungeon Generator - Tarea 1 Bases de Datos II"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.3",
    "rich>=14.1.0",
    "ruff>=0.13.3",
]
